# /caitlinch/treelikeness-metrics/code/03_empirical_data_treelikeness.R
# Caitlin Cherryh 2022

# This program will apply various tests for treelikeness to mtDNA and nDNA alignments
# This program requires IQ-Tree2 (2.2-beta or above), fast TIGER, phylogemetric, and SplitsTree (4.17.2 or above).

# Paper:
#   Oaks, J.R. (2011), A time-calibrated species tree of Crocodylia reveals a recent radiation of the true crocodiles. Evolution, 65: 3285-3297. https://doi.org/10.1111/j.1558-5646.2011.01373.x

# Data available from: 
#   Oaks, Jamie R (2011), Data from: A time-calibrated species tree of Crocodylia reveals a recent radiation of the true crocodiles, Dryad, Dataset, https://doi.org/10.5061/dryad.5k9s0



#### 1. Set parameters ####
## Directories
# local_directory         <- Directory where alignments will be saved/treelikeness metrics will be run
# results_directory       <- Directory where collated results from the treelikeness test statistics will be saved
# oaks_directory          <- Directory containing mtDNA and nDNA alignment files 
#                             Generated by script code/00_Oaks2011_prepare_empirical_data.R from caitlinch/treelikeness-metrics github repository
# repo_directory          <- Location of caitlinch/treelikeness-metrics github repository (for access to functions)

## Executable paths
# iqtree2_path            <- Path to IQ-Tree2.2-beta executable (this is the IQ-Tree2 release containing Alisim)
# fast_TIGER_path         <- Path to fast TIGER executable
# phylogemetric_path      <- Path to phylogemetric executable
# splitstree_path         <- Path to SplitsTree 4 version 4.17.2 or above

## Run parameters
# num_cores               <- Number of parallel threads to use at once

run_location = "local"
if (run_location == "local"){
  # Directories
  local_directory <- "/Users/caitlincherryh/Documents/C2_TreelikenessMetrics/"
  results_directory <- paste0(local_directory, "01_results/")
  oaks_directory <- "/Users/caitlincherryh/Documents/C2_TreelikenessMetrics/00_data_oaks2011/"
  repo_directory <- "/Users/caitlincherryh/Documents/Repositories/treelikeness-metrics/"
  
  # Executable paths
  iqtree2_path <- "iqtree2.2-beta"
  splitstree_path <- "/Applications/SplitsTree/SplitsTree.app/Contents/MacOS/JavaApplicationStub"
  phylogemetric_path <- "/Users/caitlincherryh/Documents/Executables/phylogemetric/phylogemetric_executable"
  fast_TIGER_path <- "/Users/caitlincherryh/Documents/Executables/fast_TIGER-0.0.2/DAAD_project/fast_TIGER"
  
  # Run parameters
  num_cores <- 1
} else if (run_location == "soma"){
  # Directories
  local_directory <- "/data/caitlin/treelikeness_metrics/"
  results_directory <- local_directory
  oaks_directory <- "/data/caitlin/treelikeness_metrics/Oaks2011/"
  repo_directory <- "/data/caitlin/treelikeness_metrics/"
  
  # Executable paths
  iqtree2_path <- "/data/caitlin/linux_executables/iqtree-2.2.0-Linux/bin/iqtree2"
  splitstree_path <- "/home/caitlin/splitstree4/SplitsTree"
  phylogemetric_path <- "/home/caitlin/.local/bin/phylogemetric"
  fast_TIGER_path <- "/data/caitlin/linux_executables/fast_TIGER/fast_TIGER"
  
  # Run parameters
  num_cores <- 50
}



#### 2. Prepare analyses ####
# Open packages
library(parallel)

# Source functions from caitlinch/treelikeness_metrics
source(paste0(repo_directory, "code/func_metrics.R"))
source(paste0(repo_directory, "code/func_data_analysis.R"))



#### 3. Construct parameters dataframe for empirical alignments ####
# Create filename for Oaks 2011 parameters csv
oaks_csv_file <- paste0(results_directory, "Oaks2011_parameters.csv")

# Find or create the Oaks 2011 parameters csv
if (file.exists(oaks_csv_file)){
  oaks_df <- read.csv(oaks_csv_file)
} else {
  ## Find the genes for analysis
  # Collect all alignments from Oaks 2011 dataset
  all_files <- list.files(oaks_directory, recursive = TRUE)
  # Get all genes (will have the phrase "gene_alignments" in file name)
  all_genes <- grep("gene_alignments", all_files, value = TRUE)
  # Make list of the names of the genes you want to extract
  gene_names <- c("cmos", "CYTB", "ND2", "ND3")
  # Identify the files for those genes
  run_genes <- grep(paste(gene_names, collapse = "|"), all_genes, value = TRUE)
  # Extract the partitions of interest for those genes
  partition_genes <- grep("_12", run_genes, value = TRUE, invert = TRUE)
  # Extract the subsets of interest for those genes
  subset_genes <- c(grep("8taxa", partition_genes, value = TRUE), grep("23taxa", partition_genes, value = TRUE), grep("79taxa", partition_genes, value = TRUE))
  # Add location to get full file path to each gene 
  subset_gene_paths <- paste0(oaks_directory, subset_genes)
  
  ## Construct a dataframe containing information for analysis
  # Identify whether each gene is mtDNA or nDNA
  gene_type <- gsub("_gene_alignments", "", unlist(strsplit(subset_genes, "/"))[c(T,F)])
  # Get just the file name of each alignment file (include no part of the file path)
  gene_file_name <- basename(subset_genes)
  # Get the name of each gene
  gene_split <- strsplit(gene_file_name, "_")
  gene_name <- unlist(lapply(gene_split, `[[`, 1))
  # Identify the number of taxa in each gene
  gene_num_taxa <- as.numeric(gsub("taxa.fa", "", grep("taxa", unlist(strsplit(gene_file_name, "_")), value = TRUE)))
  # Identify the partitioning scheme for each gene
  codon_partitions <- gene_file_name
  codon_partitions[grep("_1_", gene_file_name)] <- "1"
  codon_partitions[grep("_2_", gene_file_name)] <- "2"
  codon_partitions[grep("_3_", gene_file_name)] <- "3"
  codon_partitions[grep("_1_|_2_|_3_", gene_file_name, invert = TRUE)] <- "All"
  # Assemble into a dataframe
  oaks_df <- data.frame(row_id = 1:length(subset_gene_paths),
                        uid = paste0(gene_name, "_", gene_type, "_", gene_num_taxa, "_", codon_partitions), 
                        gene_name = gene_name, 
                        num_taxa = gene_num_taxa, 
                        codon_position = codon_partitions, 
                        DNA_type = gene_type, 
                        old_alignment_path = subset_gene_paths)
  # Save dataframe
  write.csv(oaks_df, file = oaks_csv_file, row.names = FALSE)
}



#### 4. Copy alignments and save the parameters for each alignment ####
# Make a new folder for the Oaks 2011 analyses
copy_directory <-  paste0(results_directory, "Oaks2011/")
if (dir.exists(copy_directory) == FALSE){dir.create(copy_directory)}
# Make a new column in the dataframe. This column is the location where each alignment will be copied and stored
oaks_df$output_alignment_path <- paste0(copy_directory, oaks_df$uid, "/", oaks_df$uid, "_output_alignment.fa")
oaks_df$parameters_path <- paste0(copy_directory, oaks_df$uid, "/", oaks_df$uid, "_parameters.csv")
# Feed each row into the function to copy the alignment and save the corresponding alignment parameters 
lapply(1:nrow(oaks_df), copy.empirical.alignment, data_df = oaks_df)



#### 5. Apply tests for treelikeness to each empirical alignment ####
# Get list of all the Oaks 2011 alignments to run
all_oaks_alignments <- oaks_df$output_alignment_path
# Apply treelikeness metrics to all alignments 
mclapply(all_oaks_alignments, treelikeness.metrics.empirical, 
         iqtree2_path, splitstree_path, phylogemetric_path, fast_TIGER_path, 
         supply_number_of_taxa = FALSE, number_of_taxa = NA, 
         num_iqtree2_threads = "AUTO", num_iqtree2_scf_quartets = 100, 
         iqtree_substitution_model = "MFP", distance_matrix_substitution_method = "JC69", 
         num_phylogemetric_threads = NA, tree_proportion_remove_trivial_splits = TRUE, 
         run_splitstree_for_tree_proportion = TRUE, sequence_format = "DNA", 
         apply.TIGER = TRUE, redo = FALSE, 
         mc.cores = num_cores)

# Collect and collate results
oaks_list <- mclapply(all_oaks_alignments, collate.empirical.treelikeness.results, mc.cores = num_cores)
# Remove NULL objects in list (indicates treelikeness metrics csv does not exist for this alignment)
keep_indexes <- which(!sapply(oaks_list, is.null))
oaks_list_filtered <- oaks_list[keep_indexes]
# Save output dataframe
oaks_tl_df <- as.data.frame(do.call("rbind", oaks_list_filtered))
oaks_df_name <- paste0(results_directory, "Oaks2011_treelikeness_metrics_collated_results.csv")
write.csv(oaks_tl_df, oaks_df_name, row.names = FALSE)
