# /caitlinch/treelikeness-metrics/code/03_empirical_data_treelikeness.R
# Caitlin Cherryh 2022

# This program will apply various tests for treelikeness to mtDNA and nDNA alignments
# This program requires IQ-Tree2 (2.2-beta or above), fast TIGER, phylogemetric, and SplitsTree (4.17.2 or above).

# Paper:
#   Oaks, J.R. (2011), A time-calibrated species tree of Crocodylia reveals a recent radiation of the true crocodiles. Evolution, 65: 3285-3297. https://doi.org/10.1111/j.1558-5646.2011.01373.x

# Data available from: 
#   Oaks, Jamie R (2011), Data from: A time-calibrated species tree of Crocodylia reveals a recent radiation of the true crocodiles, Dryad, Dataset, https://doi.org/10.5061/dryad.5k9s0




#### 1. Set parameters ####
## Directories
# local_directory         <- Directory where alignments will be saved/treelikeness metrics will be run
# results_directory       <- Directory where collated results from the treelikeness test statistics will be saved
# oaks_directory          <- Directory containing mtDNA and nDNA alignment files 
#                             Generated by script code/00_Oaks2011_prepare_empirical_data.R from caitlinch/treelikeness-metrics github repository
# repo_directory          <- Location of caitlinch/treelikeness-metrics github repository (for access to functions)

## Executable paths
# iqtree2_path            <- Path to IQ-Tree2.2-beta executable (this is the IQ-Tree2 release containing Alisim)
# fast_TIGER_path         <- Path to fast TIGER executable
# phylogemetric_path      <- Path to phylogemetric executable
# splitstree_path         <- Path to SplitsTree 4 version 4.17.2 or above

## Run parameters
# num_cores               <- Number of parallel threads to use at once

run_location = "local"
if (run_location == "local"){
  # Directories
  local_directory <- "/Users/caitlincherryh/Documents/C2_TreelikenessMetrics/"
  results_directory <- paste0(local_directory, "01_results/")
  oaks_directory <- "/Users/caitlincherryh/Documents/C2_TreelikenessMetrics/00_data_oaks2011/"
  repo_directory <- "/Users/caitlincherryh/Documents/Repositories/treelikeness-metrics/"
  
  # Executable paths
  iqtree2_path <- "iqtree2.2-beta"
  splitstree_path <- "/Applications/SplitsTree/SplitsTree.app/Contents/MacOS/JavaApplicationStub"
  phylogemetric_path <- "/Users/caitlincherryh/Documents/Executables/phylogemetric/phylogemetric_executable"
  fast_TIGER_path <- "/Users/caitlincherryh/Documents/Executables/fast_TIGER-0.0.2/DAAD_project/fast_TIGER"
  
  # Run parameters
  num_cores <- 1
} else if (run_location == "soma"){
  # Directories
  local_directory <- "/data/caitlin/treelikeness_metrics/"
  results_directory <- local_directory
  oaks_directory <- "/data/caitlin/treelikeness_metrics/Oaks2011/"
  repo_directory <- "/data/caitlin/treelikeness_metrics/"
  
  # Executable paths
  iqtree2_path <- "/data/caitlin/linux_executables/iqtree-2.2.0-Linux/bin/iqtree2"
  splitstree_path <- "/home/caitlin/splitstree4/SplitsTree"
  phylogemetric_path <- "/home/caitlin/.local/bin/phylogemetric"
  fast_TIGER_path <- "/data/caitlin/linux_executables/fast_TIGER/fast_TIGER"
  
  # Run parameters
  num_cores <- 50
}



#### 2. Prepare analyses ####
# Open packages
library(parallel)

# Source functions from caitlinch/treelikeness_metrics
source(paste0(repo_directory, "code/func_metrics.R"))
source(paste0(repo_directory, "code/func_data_analysis.R"))



#### 3. Construct parameters dataframe for empirical alignments ####





#### 4. Apply tests for treelikeness to each empirical alignment ####
  # Open output df and get names of alignments
  exp1_op_file <- paste0(results_directory, grep("rerun", grep("exp1", grep("file_output_paths", results_files, value = TRUE), value = TRUE), value = TRUE, invert = TRUE))
  exp1_op_df <- read.csv(exp1_op_file, stringsAsFactors = FALSE)
  # Exp1 encountering errors in all cores. Not running properly. Remove all alignments with substitution rate 1e-04 and 0.001 (too many identical sequences)
  exp1_op_df <- exp1_op_df[(exp1_op_df$tree_depth != 1e-04 & exp1_op_df$tree_depth != 1e-03),]
  # Get list of alignments
  exp1_als <- exp1_op_df$output_alignment_file
  # Apply treelikeness metrics to all alignments 
  mclapply(exp1_als, treelikeness.metrics.simulations, iqtree2_path, splitstree_path, phylogemetric_path, fast_TIGER_path, 
           supply_number_of_taxa = FALSE, number_of_taxa = NA, num_iqtree2_threads = "AUTO", 
           num_iqtree2_scf_quartets = 100, iqtree_substitution_model = "JC", 
           distance_matrix_substitution_method = "JC69", num_phylogemetric_threads = NA,
           tree_proportion_remove_trivial_splits = TRUE, run_splitstree_for_tree_proportion = TRUE,
           sequence_format = "DNA", return_collated_data = TRUE, apply.TIGER = TRUE,
           redo = FALSE, save_timers = TRUE, 
           mc.cores = num_cores)
  
  # Collect and collate results
  exp1_list <- mclapply(exp1_als, collate.treelikeness.results, experiment_number = 1, mc.cores = num_cores)
  # Remove NULL objects in list (indicates treelikeness metrics csv does not exist for this alignment)
  keep_indexes <- which(!sapply(exp1_list, is.null))
  exp1_list_filtered <- exp1_list[keep_indexes]
  # Save output dataframe
  exp1_df <- as.data.frame(do.call("rbind", exp1_list_filtered))
  exp1_df_name <- paste0(results_directory, "exp1_treelikeness_metrics_collated_results.csv")
  write.csv(exp1_df, exp1_df_name, row.names = FALSE)
