# caitlinch/treelikeness_metrics/supp_code/suppA_func_simulating_alignment.R
# Caitlin Cherryh 2023

#This file contains functions to simulate DNA multiple sequence alignments with varying levels of treelikeness
# Some functions require IQ-Tree2 (2.2-beta or above), or ms



## Load required packages
library(ape)
library(phangorn)
library(TreeSim)



#### Utility functions ####
divisors <- function(x){
  # Function to find all divisors of x using modulo division
  y <- 1:x
  # If remainder is 0, then y is a divisor of x. Keep all divisors
  d = y[x%%y == 0]
  return(d)
}



#### Functions to generate and manipulate trees ####
generate.random.trees <- function(num_trees, num_taxa, tree_depth, output_filepath = NA){
  # This function generates n random trees with m taxa (where n is set by num_trees and m is set by num_taxa)
  # Using the `ape` function `rtree`, trees are generated by randomly splitting the edges

  # Generate random trees
  trees <- rmtree(num_trees, num_taxa)

  # Scale the depth of each tree (so the total depth is set according to the tree_depth parameter)
  for (i in 1:num_trees){
    t <- trees[[i]]
    t$edge.length <- t$edge.length * (tree_depth / max(branching.times(t)))
    trees[[i]] <- t
  }

  # If output filepath is provided, save trees to file
  if (!is.na(output_filepath) == TRUE){
    write.tree(trees, file = output_filepath)
  }
}



#### Functions to generate partition files ####
partition.random.trees <- function(num_trees, al_length, sequence_type, models = NA, rescaled_tree_lengths = NA, output_filepath){
  # This function generates a charpartition file for n genes (where n is num_trees) of length al_length/n

  # Generate charsets
  # Find start and end point of each gene in the total alignment length
  gene_start_points <- seq(1, al_length, (al_length/num_trees))
  gene_end_points <- seq((al_length/num_trees), al_length, (al_length/num_trees))
  # Name genes
  gene_names <- sprintf("gene_%05d",1:num_trees)
  # Paste arguments together into charset lines
  csets <- paste0("\tcharset ", gene_names, " = ", sequence_type, ", ", format(gene_start_points, scientific = FALSE, trim = TRUE), "-",
                  format(gene_end_points, scientific = FALSE, trim = TRUE), ";")

  # Generate model arguments
  if (!is.na(models) == TRUE){
    # If models have been provided, generate a charpartition line for the partition file
    # "models" should be a list of models with one model corresponding to one gene, or 1 model to be applied to all genes
    if (is.na(rescaled_tree_lengths) == TRUE){
      # If no rescaled_tree_lengths are provided, create the chpartitions by directly assembling the models and gene names
      gene_models <- paste0(models, ":", gene_names)
    } else if (is.na(rescaled_tree_lengths) == FALSE){
      # If rescaled_gene_lengths are provided, add them to the gene_models vector.
      # This allows different genes to have different evolutionary rates (by specifying gene-specific tree lengths within the charpartition command)
      gene_models <- paste0(models, ":", gene_names, "{", rescaled_tree_lengths, "}")
    }
    # Assemble all sections of the charpartition command
    cpart <- paste0("\tcharpartition genes = ", paste(gene_models, collapse = ", "), ";")
  } else{
    # If no models provided, do not create a charpartition line for the partition file
    cpart <- NULL
  }

  # Assemble components into partition file
  c_file <- c("#nexus", "begin sets;", csets, cpart, "end;")

  # Write partition file
  write(c_file, file = output_filepath)
}



#### Functions to simulate alignments in Alisim (IQ-Tree2) ####
alisim.topology.unlinked.partition.model <- function(
    iqtree_path,
    alisim_output_alignment,
    partition_file_path,
    trees_path,
    output_format = "fasta",
    sequence_type = "DNA"
) {
  # This function uses the topology-unlinked partition model in Alisim to
  # generate a sequence alignment containing multiple concatenated genes, each
  # with its own tree topology and branch lengths

  # Assemble function call
  function_call <- paste0(
    iqtree_path,
    " --alisim ",
    alisim_output_alignment,
    " -t ",
    trees_path,
    " -q ",
    partition_file_path,
    " --seqtype ",
    sequence_type,
    " -af ",
    output_format
  )
  # Invoke the OS command and call IQ-Tree
  system(function_call)
}



#### Functions to process a single row from the parameters matrix and ####
#### estimate an alignment using the parameters in that row           ####
random.trees.generate.alignment <- function(
    row_id, output_directory, iqtree2_path, experiment_params
){
  ## Function to generate a single alignment given a row SA1 dataframe
  # The alignment will be simulated from a number of random trees

  # Extract row given the row number
  row <- experiment_params[row_id, ]

  # Create a new folder to store the results in this experiment from
  #   (and a file to keep a csv of the parameter values in)
  if (is.na(row$uid) == FALSE){
    row_folder <- paste0(
      output_directory,
      row$uid,
      "/"
    )
    row_csv_path <- paste0(
      row_folder,
      row$uid,
      "_parameters.csv"
    )
  } else if (is.na(row$uid) == TRUE & is.na(row$num_reps) == FALSE){
    row_folder <- paste0(
      output_directory,
      sprintf("%05d", row$num_trees),
      "_",
      sprintf("%04d", row$num_taxa),
      "_",
      sprintf("%03d", row$num_reps),
      "_",
      row$tree_depth,
      "/"
    )
    row_csv_path <- paste0(
      row_folder,
      sprintf("%05d", row$num_trees),
      "_",
      sprintf("%04d", row$num_taxa),
      "_",
      sprintf("%03d", row$num_reps),
      "_",
      row$tree_depth,
      "_parameters.csv"
    )
  } else {
    row_folder <- paste0(
      output_directory,
      sprintf("%05d", row$num_trees),
      "_",
      sprintf("%04d", row$num_taxa),
      "_",
      NA,
      "_",
      row$tree_depth,
      "/"
    )
    row_csv_path <- paste0(
      row_folder,
      sprintf("%05d", row$num_trees),
      "_", sprintf("%04d", row$num_taxa),
      "_",
      NA,
      "_",
      row$tree_depth,
      "_parameters.csv")
  }
  if (dir.exists(row_folder) == FALSE){dir.create(row_folder)}

  # Create path for output alignment file
  output_alignment_file <- paste0(row_folder, row$output_alignment_file, ".fa")

  # If the output alignment does not already exist, generate the output alignment
  if (file.exists(output_alignment_file) == FALSE){
    # Generate the random trees
    generate.random.trees(
      num_trees = row$num_trees,
      num_taxa = row$num_taxa,
      tree_depth = row$tree_depth,
      output_filepath = paste0(row_folder, row$tree_file)
    )
    # Generate the partition file
    partition.random.trees(
      num_trees = row$num_trees,
      al_length = row$total_alignment_length,
      sequence_type = row$sequence_type,
      models = row$alisim_gene_models,
      rescaled_tree_lengths = row$alisim_gene_tree_length,
      output_filepath = paste0(row_folder, row$partition_file)
    )
    # Call alisim in IQ-Tree2 to simulate DNA along the trees given the partition file
    alisim.topology.unlinked.partition.model(
      iqtree_path = iqtree2_path,
      alisim_output_alignment = paste0(row_folder, row$output_alignment_file),
      partition_file_path = paste0(row_folder, row$partition_file),
      trees_path = paste0(row_folder, row$tree_file),
      output_format = "fasta",
      sequence_type = row$sequence_type
    )
  }
  if (file.exists(row_csv_path) == FALSE){
    # If parameter csv does not exist, finalise parameter csv for output as csv file
    row$row_id <- row_id
    row$tree_file <- paste0(row_folder, row$tree_file)
    row$partition_file <- paste0(row_folder, row$partition_file)
    row$output_alignment_file <- output_alignment_file
    output_row <- row[, c(
      "row_id",
      "num_reps",
      "num_taxa",
      "num_trees",
      "tree_depth",
      "uid",
      "alisim_gene_models",
      "alisim_gene_tree_length",
      "total_alignment_length",
      "sequence_type",
      "tree_file",
      "partition_file",
      "output_alignment_file"
    )]
    write.csv(output_row, file = row_csv_path, row.names = FALSE)
  } else if (file.exists(row_csv_path) == TRUE) {
    # If output parameter csv exists, read it in
    output_row <- read.csv(row_csv_path)
  }

  # Return the dataframe row of parameters for this replicate
  return(output_row)
}




